ENT.Type = 'anim'
ENT.Base = 'base_gmodentity'
ENT.PrintName = '--- На новый год)'
ENT.Author = 'Kot'
ENT.Contact = ''
ENT.Purpose = ''
ENT.Instructions = ''
ENT.Spawnable = true
ENT.AdminSpawnable = false
ENT.Category = '!Rephyx.tech | Утилиты'
ENT.Editable = false
ENT.Carry = false
ENT.noDrag = true 
